### ISSUE TITLE
Page for Users Management

### ISSUE THREAD

**Issue by ofvalentine** [sopra-fs22-group-4/group-matcher-frontend#15]

**Comment by hk-kaden-kim** [comment]
@ofvalentine what is the user's management page?
is it related with the edit button next to every student?
<img width="455" alt="Screen Shot 2022-05-15 at 12 36 59 AM" src="https://user-images.githubusercontent.com/91096475/168450205-9bf8fb39-6765-4232-a495-4886c0984c85.png">

**Comment by ofvalentine** [comment]
> @ofvalentine what is the user's management page? is it related with the edit button next to every student? <img alt="Screen Shot 2022-05-15 at 12 36 59 AM" width="455" src="https://user-images.githubusercontent.com/91096475/168450205-9bf8fb39-6765-4232-a495-4886c0984c85.png">

This table moved to a subpage of the matcher page (see the component called Students) where the admin can review, edit and add all students

Closed with 1c72a8a5fd23ebc632c6308848f8d0e69c7a749c
