### ISSUE TITLE
Allow adding a text question to the matching quiz

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-frontend#8]
Create a form component with:
- [x] "Question Title" field with validation (non-empty, min/max length)
- [ ] The admin can customize / put limitations on the text answer via the following _optional_ fields:
   - [ ] Limit text answer length - set up a numeric input field for max num. of words or max num. of characters
   - [ ] Limit characters type - set up a multiple-choice field with a list of possible input types (alphabet, numeric, special characters...)
- [x] "Submit" button that is disabled (not clickable) until the user provides valid input to the title field
- [x] Clicking the submit button triggers a POST request to the /matcher/{matcherId}/question endpoint
- [x] If the question was created successfully, display a confirmation message and redirect to the admin dashboard where all questions are displayed
- [ ] If an error occurred, display an error message (ideally with the relevant next step)

**Comment by Akshay-008** [comment]
Admin can add a text-based question using forms.
